
[cursor]
vi_mode_style = "Underline"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[window]
dynamic_padding = false
dynamic_title = false
opacity = 0.5

[window.padding]
x = 0
y = 0

[general]
import = ["/home/martin/.config/alacritty/catppuccin-mocha.toml"]
