arch = {
    packages = [
        # core linux
        "base",
        "base-devel",
        "grub",
        "os-prober",
        "linux",
        "linux-firmware",
        "linux-headers",
        "pacman-contrib",

        # docs
        "man-db",
        "man-pages",
        "tldr",

        # required shell stuff
        "zsh",
        "yay",
        "metapac",

        # connectivity
        "openssh",
        "iwd",

        # low level control (platform independent)
        "fwupd",
        "dmidecode",
    ]
}
