arch = [
    # pipewire
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "gst-plugin-pipewire",
    "lib32-pipewire",
    "alsa-utils",
    "alsa-tools",

    # essentials
    "ghostty",
    "nautilus",

    # daily drivers
    "zen-browser-bin",
    "obsidian",
    "slack-desktop",
    "spotify-launcher",

    # misc
    "zoom",
    "helium-browser-bin",
    "vesktop-bin",

    # misc utilities
    "qalculate-gtk",
    "gimp",
    "mpv",
    "xournalpp",
    "zathura",
    "zathura-pdf-poppler",
    "typst",
    "postgresql",
    "jupyterlab",
    "patchelf",
    "arduino-cli",

    # virtmanger
    "qemu-full",
    "dnsmasq",
    "libvirt",
    "virt-manager",
]
