arch = [
    "sunshine-bin",
    "v4l2loopback-dkms",

    # nvidia
    "nvidia-open-dkms",
    "nvidia-utils",
    "lib32-nvidia-utils",
    "libva-nvidia-driver",
    "nvidia-container-toolkit",

    # intel
    "intel-ucode",

    # csl dd support
    "hid-fanatecff-dkms",
    "oversteer",

    # ksp
    "ckan-bin",
]
