arch = [
    # zshrc
    "oh-my-posh-bin",
    "ripgrep",
    "eza",
    "bat",
    "direnv",
    "fzf",
    "zoxide",
    "yazi",
    "reflector",

    # yazi optional deps (also just good)
    "jq",
    "7zip",
    "fd",
    "imagemagick",

    # tmux
    "tmux",
    "tmux-plugin-manager",

    # neovim
    "neovim",
    "lazygit",
    "tree-sitter-cli",

    # good utils
    "github-cli",
    "fastfetch",
    "btop",
    "stress",
    "syncthing",
    "termdown",
    "tree",
    "unzip",
    "zip",
    "wget",
    "rsync",
    "impala",

    # languages
    "clang",
    "go",
    "typescript",

    # tooling
    "cmake",
    "gdb",
    "inetutils",
    "bind",      # dig, etc
    "sshfs",
    "stow",
    "valgrind",
    "just",

    # docker
    "docker",
    "docker-buildx",
    "docker-compose",

    # deps
    "python-dbus-next",
]
